name: gotrip_mobile
description: A beautiful travel app for discovering and booking amazing trips.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.0.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  intl: ^0.19.0
  provider: ^6.0.0
  http: ^1.1.0
  shared_preferences: ^2.2.0
  flutter_svg: ^2.0.10
  badges: ^3.1.2
  supabase_flutter: ^2.0.0
  image_picker: ^1.2.0
  cached_network_image: ^3.3.0
  web: ^0.5.0
  tflite_flutter: ^0.11.0
  image: ^4.1.3
  path_provider: ^2.1.0
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/data/
    - assets/models/
